import type { Course } from './course';
import type { VideoAnalysis, VideoMarker } from './video';

export function normalisePoint(x: number, y: number, width: number, height: number) { return { x: Math.max(0, Math.min(1, x / Math.max(1, width))), y: Math.max(0, Math.min(1, y / Math.max(1, height))) }; }
export function markerAt(analysis: VideoAnalysis, kind: VideoMarker['kind'], timeSec: number, point: { x: number; y: number } | null, gateNumber: number | null = null): VideoMarker { return { id: crypto.randomUUID(), kind, timeSec: Math.max(0, Math.min(analysis.durationSec, timeSec)), gateNumber, point, source: 'manual', confidence: 1 }; }
export function trackingToCourse(analysis: VideoAnalysis, course: Course): { x: number; y: number; confidence: number }[] { const start = analysis.startMarker?.point; const finish = analysis.finishMarker?.point; if (!start || !finish) return []; const dx = finish.x - start.x; const dy = finish.y - start.y; if (Math.hypot(dx, dy) < 1e-9) return []; return analysis.tracking.map((s) => ({ x: Math.max(0, Math.min(course.width, ((s.point.x - start.x) / dx) * course.width)), y: Math.max(0, Math.min(course.length, ((s.point.y - start.y) / dy) * course.length)), confidence: s.confidence })); }
export function draftRunTiming(analysis: VideoAnalysis): number | null { if (!analysis.startMarker || !analysis.finishMarker) return null; const duration = analysis.finishMarker.timeSec - analysis.startMarker.timeSec; return duration > 0 ? duration : null; }
export function applyProcessorJob(analysis: VideoAnalysis, job: { id: string; status: string; progress: number; duration_sec?: number | null; width?: number | null; height?: number | null; fps?: number | null; tracking: { time_sec: number; x: number; y: number; confidence: number; source: 'auto' | 'manual' }[]; confidence: number; error?: string | null }): VideoAnalysis { const status = job.status === 'completed' ? 'ready' : job.status === 'cancelled' ? 'cancelled' : job.status === 'failed' ? 'failed' : 'processing'; return { ...analysis, processorJobId: job.id, status, progress: job.progress, durationSec: job.duration_sec ?? analysis.durationSec, width: job.width ?? analysis.width, height: job.height ?? analysis.height, fps: job.fps ?? analysis.fps, tracking: job.tracking.map((p) => ({ timeSec: p.time_sec, point: { x: p.x, y: p.y }, confidence: p.confidence, source: p.source })), confidence: job.confidence, error: job.error ?? null, updatedAt: new Date().toISOString() }; }
export function updateTrackingPoint(analysis: VideoAnalysis, index: number, x: number, y: number): VideoAnalysis { if (!analysis.tracking[index]) return analysis; const tracking = analysis.tracking.map((sample, i) => i === index ? { ...sample, point: { x: Math.max(0, Math.min(1, x)), y: Math.max(0, Math.min(1, y)) }, confidence: 1, source: 'manual' as const } : sample); return { ...analysis, tracking, updatedAt: new Date().toISOString() }; }
